### ISSUE TITLE
How to upload files using GraphQL Multipart Request Specification

### ISSUE THREAD

**Issue by ybtam** [Sukairo-02/drizzle-graphql#23]
How to create a custom mutation with GraphQL Multipart Request Specification in arg?

What I am looking for
```
uploadMedia: {
  args: {
    file: { type: GraphQLFile  }
  },
  resolve: (_, args) => uploadMedia(args),
  type: GraphQLBoolean,
},
```

**Comment by Sukairo-02** [comment]
Well, you just create custom schema, reuse queries & types generated by drizzle-graphql, and then for mutations you spread generated mutations into an object and add mutation you described in there. Is there something I'm missing?

**Comment by ybtam** [comment]
that is what I tried, but there is no GrapahQLFile type in drizzle-graphql. How do I structure the args to consume standard File or Blob object?

I am using graphql-yoga https://the-guild.dev/graphql/yoga-server/docs/features/file-uploads.

**Comment by ybtam** [comment]
Alright just realised where I went wrong, didn't realise that I was using graphql/type to build the schema 😅
